name: fmtc_example
description: The example application for 'flutter_map_tile_caching', showcasing
  it's functionality and use-cases.
publish_to: "none"

version: 6.2.0+2

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  badges: ^3.1.1
  better_open_file: ^3.6.4
  flutter:
    sdk: flutter
  flutter_foreground_task: ^6.0.0
  flutter_map: ^5.0.0
  flutter_map_tile_caching:
    path: ../
  flutter_speed_dial: ^7.0.0
  google_fonts: ^5.0.0
  http: ^1.0.0
  intl: ^0.18.1
  latlong2: ^0.9.0
  osm_nominatim: ^2.0.1
  path: ^1.8.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  stream_transform: ^2.0.0
  validators: ^3.0.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - currentAppVersion.txt
